### ISSUE TITLE
Own Home Multi-tenant

### ISSUE THREAD

**Issue by rdrgporto** [wtakase/kibana-own-home#104]
Hi, everyone

I have managed to integrate **Kibana** & **Elasticsearch** & **Search Guard** & **Own Home**. When someone logs in, they have their own **Kibana** index to store their dashboards and visualizations.

**Search Guard** provides a tool called **Multi-tenancy** that allows a user to "jump" from one tenant to another.

So that, I would like to know if there is some possibility to achieve it with **Own Home**?

Thank you very much in advance,

Regards 🖖

**Comment by wtakase** [comment]
What do you mean `jump`?
Do you want to switch kibana.index?

For example, there are two users, `user1` and `user2`, and there are three kibana.index, `.kibana_user1`, `.kibana_user2`, `.kibana_public`.
With Own Home, `user1` can see `.kibana_user1` and `.kibana_public`.
And `user2` can see `.kibana_user2` and `.kibana_public`.

**Comment by rdrgporto** [comment]
Hi, @wtakase 

In your example, I would like **user1** could access to **.kibana_user2** too. My intention is to have an **admin user** who can switch over tenants.

Is it possible?

Thanks in advance 😃 ,

Regards

**Comment by wtakase** [comment]
What about this information?
https://github.com/wtakase/kibana-own-home/issues/78#issuecomment-368781744

**Comment by rdrgporto** [comment]
Hi @wtakase,

Thanks for the information.

Regards
