### ISSUE TITLE
Short url

### ISSUE THREAD

**Issue by psaiz** [wtakase/kibana-own-home#11]
Hi Wataru, 

I'm having issues with the shortening of the url. When I click on 'Short url', I see that there is a call being made to kibana like https://&lt;server>/shorten However, that doesn't seem to do any call to elasticsearch. 

Then, when I go to the short url ( something like   https://&lt;server>/goto/3303684adf0a0fd8c2baa01ef0e0aa5c ), I see that it does an elasticsearch call to retrieve /.kibana_default/url/3303684adf0a0fd8c2baa01ef0e0aa5c, which indeed it does not exist.  

It looks like the 'short url' does not save the object. Do you have the same issue? I'm running own_home@5.2.0-2

Cheers, 
pablo

**Comment by wtakase** [comment]
Thanks for the report.
I will check it.

**Comment by wtakase** [comment]
Sorry for the delay.
What about the [patch](https://github.com/wtakase/kibana-own-home/commit/3f8bcc908bc7882a74d40c135f121a23ace4ebc7)?

**Comment by psaiz** [comment]
Hi Wataru, 

Thanks a lot for the reply and for the patch. I'm afraid that it doesn't solve the issue. The request to 'shorten' still does not write anything into the index. I see the request being made, but it does not save anything in the index.

If I restart kibana, disabling the own_home plugin, then the short url works.

Cheers,
pablo

**Comment by wtakase** [comment]
Do you set `own_home.explicit_kibana_index_url.enabled: true`?
In this case I confirmed `shorten` doesn't work.
Otherwise, it works with the patch.

**Comment by psaiz** [comment]
Thanks! That solves the issue. 
Thanks again, 
pablo
