### ISSUE TITLE
Search Guard

### ISSUE THREAD

**Issue by juhwankim** [wtakase/kibana-own-home#12]
Hi there,

I'm currently using the Search Guard plugin.
I came across that you have partly confirmed that Own-home works with Search Guard in the issue here: [issues/6](https://github.com/wtakase/kibana-own-home/issues/6)
Do you have an instruction or a guide for intergrating Own-home with Search Guard?

Thank you in advance.

**Comment by wtakase** [comment]
Own Home stores Kibana objects to user/group based `kibana.index` such as `.kibana_user01`, `.kibana_public`.
You can do access control of the indices by Search Guard.

I confirmed this plugin works with Search Guard v2.

I describe my procedure.

For the first step, I put empty .kibana-devnull index:
```
$ curl -XPUT https://admin:xxxxx@localhost:9200/.kibana-devnull/
```

Then I added some lines to sg_action_groups.yml:
```
KIBANA_READ:
  - READ
  - "indices:admin/mappings/fields/get*"
  - "indices:admin/validate/query*"
  - "indices:admin/get*"
  - "indices:admin/refresh*"
  - "indices:admin/exists*"
```

Let's consider some cases.
In the case that each user has a own `kibana.index` and each index allows access only from the owner, you can configure sg_roles.yml and sg_roles_mapping.yml as follows:

sg_roles.yml
```
sg_own_kibana_index:
  indices:
    '?kibana_${user_name}':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ
```

sg_roles_mapping.yml
```
sg_own_kibana_index:
  users:
    - '*'
```

In another case that all users can read `.kibana_public` and only user01 can write it, you can configure as follows:

sg_roles.yml
```
sg_kibana_public_readonly:
  indices:
    '?kibana_public':
      '*':
        - KIBANA_READ
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_kibana_public:
  indices:
    '?kibana_public':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ
```

sg_roles_mapping.yml
```
sg_kibana_public_readonly:
  users:
    - '*'

sg_kibana_public:
  users:
    - user01
```

**Comment by juhwankim** [comment]
Thank you for the detailed explanation!
Do you write user info in the header when you send requests to elasticsearch from own_home?
Could you share the sg_config.xml settings?

These are the options I used in my kibana:
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]

own_home.proxy_user_header: x-proxy-user
own_home.elasticsearch.url: http://localhost:9200

own_home.session.isSecure: false
own_home.session.timeout: 3600000

own_home.local.groups: [ common01, common02 ]

own_home.explicit_kibana_index_url.enabled: true
own_home.explicit_kibana_index_url.proxy.url: http://localhost:15601

own_home.ldap.enabled: false
own_home.ldap.url: ldap://localhost:389
own_home.ldap.userbase: ou=People,dc=localhost
own_home.ldap.rolebase: ou=Groups,dc=localhost
own_home.ldap.search_filter: '(cn=*)'
own_home.ldap.username_attribute: cn
own_home.ldap.rolename_attribute: cn
own_home.ldap.adfs: false

**Comment by juhwankim** [comment]
Thank you for the detailed explanation!

I followed the steps, but I need your help with the issue below:
### elasticsearch.log
```
[2017-03-16T14:24:53,164][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=delko1, roles=[]] [IndexType [index=.kibana, type=config]] [Action [indices:data/read/get]] [RolesChecked [sg_own_kibana_index]]
[2017-03-16T14:24:54,173][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=delko1, roles=[]] [IndexType [index=.kibana, type=index-pattern]] [Action [indices:data/read/search]] [RolesChecked [sg_own_kibana_index]]
```
I connected with the user info(delko1),  but it tried to search the .kibana index, instead of .kibana_delko1.

Is there anything I need to change in the settings below?:
### sg_roles.yml
```
sg_own_kibana_index:
  indices:
    '?kibana_${user_name}':
      '*':
        - ALL
    '?kibana_common*':
      '*':
        - KIBANA_READ
```
### sg_roles_mapping.yml
```
sg_own_kibana_index:
  users:
    - '*'
```
### kibana.yml
```
elasticsearch.url: http://localhost:19200
#elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]

elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver

own_home.proxy_user_header: x-proxy-user
own_home.elasticsearch.url: http://localhost:9200

own_home.session.isSecure: false
own_home.session.timeout: 3600000

own_home.local.enabled: true
own_home.local.groups: [ common01, common02 ]

own_home.ldap.enabled: false
own_home.ldap.url: ldap://localhost:389
own_home.ldap.userbase: ou=People,dc=localhost
own_home.ldap.rolebase: ou=Groups,dc=localhost
own_home.ldap.search_filter: '(cn=*)'
own_home.ldap.username_attribute: cn
own_home.ldap.rolename_attribute: cn
own_home.ldap.adfs: false

own_home.explicit_kibana_index_url.enabled: true
own_home.explicit_kibana_index_url.proxy.url: http://plat-dev-04:15601
```

Test enviroment details: 
elasticsearch-5.2.2
search-guard-5:5.2.2-11
kibana-5.2.2
Own Home-5.2

**Comment by wtakase** [comment]
Could you remove `#` in front of `elasticsearch.requestHeadersWhitelist`  in kibana.yml?

**Comment by juhwankim** [comment]
I've enabled elasticsearch.requestHeadersWhitelist, and the above elasticsearch log did indeed disappear. Thanks!

But there was another issue where I can only view the data on the Own-home screen, and not in any other screens.

There wasn't any problem when I've tested on Search Guard and Own-home separately.

Please refer to the screenshot below, and it would be great if you could help me with where to check. 

* Kibana own-home screen
![image](https://cloud.githubusercontent.com/assets/23549074/24087694/a6050846-0d65-11e7-923e-aee209df26c7.png)

* Kibana other screen
![image](https://cloud.githubusercontent.com/assets/23549074/24087703/c53fd6f0-0d65-11e7-8025-6c1a5435d017.png)

**Comment by juhwankim** [comment]
The test was successful in the versions below:
* elasticsearch-2.4.0
* search-gaurd-2:2.4.0.11
* search-gaurd-ssl:2.4.0.20
* kibana-4.6.4
* own home-4.6.3

And one more thing, are you planning to add support for Search Guard v.5?
Thanks in advance!

**Comment by wtakase** [comment]
In the case using v5, could you test as follows:

delete `.kibana-devnull` index, if you have created.

add `KIBANA_READ` to sg_action_groups.yml:
```
KIBANA_READ:
  - READ
  - "indices:admin/mappings/fields/get*"
  - "indices:admin/validate/query*"
  - "indices:admin/get*"
```

sg_roles.yml:
```
sg_kibana_server:
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana*':
      '*':
        - ALL

sg_kibana_user:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '?kibana':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_own_kibana_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana_${user_name}':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ
```

sg_roles_mapping.yml:
```
sg_kibana_server:
  users:
    - kibanaserver

sg_kibana_user:
  users:
    - '*'

sg_own_kibana_index:
  users:
    - '*'
```

The `sg_kibana_user` role may not be needed.

**Comment by juhwankim** [comment]
I've tested with the settings in your comment, but it didn't work in kibana v5.2.2.

I found that an Unauthorized occures in kibana v5 when running queries with es. (It worked well on v4.)
### kibana 4.6.4
```
curl -XGET -u delko1:delko1 http://proxy01/elasticsearch/.kibana/index-pattern/_search?pretty
{"took":3,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1,"hits":[{"_index":".kibana_delko1",...}]}}

curl -XGET -u delko1:delko1 http://kibana01:5601/elasticsearch/.kibana_delko1/index-pattern/_search?pretty
{"took":3,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1,"hits":[{"_index":".kibana_delko1",...}]}}
```
### kibana 5.2.2
```
curl -XGET -u delko1:delko1 http://proxy02/elasticsearch/.kibana/index-pattern/_search?pretty
Unauthorized
		
curl -XGET -u delko1:delko1 http://**kibana02:5601**/elasticsearch/.kibana_delko1/index-pattern/_search?pretty
Unauthorized
```
I tested with the Safe Guard settings, but there were no issues there.
```
curl -XGET -u delko1:delko1 http://es_v5:9200/.kibana_delko1/_search?pretty
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
	"total" : 1,
	"successful" : 1,
	"failed" : 0
  },
  "hits" : {
	"total" : 1,
	"max_score" : 1.0,
	"hits" : [
	  {
		"_index" : ".kibana_delko1",
		"_type" : "config",
		"_id" : "5.1.2",
		"_score" : 1.0,
		"_source" : {
		  "buildNum" : 14588
		}
	  }
	]
  }
}
```
Did it work for you on versions 5 or above?
Thank you!

**Comment by wtakase** [comment]
I have a `test` user which is defined in Apache Basic auth and sg_internal_users.yml.
And I confirmed it works with v5.

Check versions:
```
# rpm -qa | egrep 'kibana|elasticsearch'
elasticsearch-5.2.2-1.noarch
kibana-5.2.2-1.x86_64
```
Check Search Guard works:
```
# curl -k -1 -XGET -u test:test https://localhost:9200/.kibana_test/_search?pretty
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : ".kibana_test",
        "_type" : "config",
        "_id" : "5.2.2",
        "_score" : 1.0,
        "_source" : {
          "buildNum" : 14723
        }
      }
    ]
  }
}
# curl -k -1 -XGET -u test:test https://localhost:9200/.kibana_wtakase/_search?pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for indices:data/read/search"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for indices:data/read/search"
  },
  "status" : 403
}
```
Check Own Home works:
```
# curl -k -1 -XGET -u test:test https://localhost/elasticsearch/.kibana/index-pattern/_search?pretty
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
```
kibana.yml
```
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
elasticsearch.username: kibana
elasticsearch.password: kibana
elasticsearch.ssl.verify: false
own_home.local.groups: [ public ]
own_home.elasticsearch.url: https://localhost:9200
own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
Apache conf
```
  RequestHeader set X-Proxy-User %{REMOTE_USER}s
  RewriteEngine on
  RewriteRule  ^/?(.*)$ http://localhost:5601/$1 [L,P]

  <Location />
    AuthType Basic
    AuthName "Basic Auth"
    AuthUserFile "/etc/httpd/conf/.htpasswd"
    Require valid-user
  </Location>
```
sg_config.yml
```
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        internalProxies: '127\.0\.0\.1|0:0:0:0:0:0:0:1'
        remoteIpHeader: 'x-forwarded-for'
        trustedProxies: '127\.0\.0\.1|0:0:0:0:0:0:0:1'
    authc:
      proxy_auth_domain:
        enabled: true
        order: 0
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
        authentication_backend:
          type: noop
      basic_internal_auth_domain: 
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
```

**Comment by juhwankim** [comment]
I adjusted the sg_config.yml settings and it worked perfectly.

Thank you so much for your help with everything.
I really appreciate it!

**Comment by uwrob** [comment]
Does this same method work with 6.2.3?
