### ISSUE TITLE
Apache configuration (solved)

### ISSUE THREAD

**Issue by folderman** [wtakase/kibana-own-home#124]
Hi All,

I am trying to use kibana-own-home in my testing environment:

Debian 9 (stretch)
ELK 6.5.0
apache 2.4.25

I would like to follow the basic setting for "Minimum configuration (for test)", however, I have found that the apache would not redirect my request from port 80 to 5601.

I am not familiar with apache, so I am pretty sure that the suggested configuration are wrongly placed (I have remove the SSL related setting).

RewriteEngine on
#SSLProxyEngine on
RewriteRule  ^/?(.*)$ http://localhost:5601/$1 [L,P]
RequestHeader set X-Proxy-User %{REMOTE_USER}s
<Location />
  #SSLRequireSSL
  AuthType Basic
  AuthName "Basic Authentication"
  AuthUserFile /path/to/htpasswd
  Require valid-user
</Location>

Can anyone tell me where I should put the above configuration?

Thanks a lot!

Kenneth

**Comment by wtakase** [comment]
```
RewriteEngine on
RewriteRule  ^/?(.*)$ http://localhost:5601/$1 [L,P]
RequestHeader set X-Proxy-User %{REMOTE_USER}e
<Location />
  AuthType Basic
  AuthName "Basic Authentication"
  AuthUserFile /path/to/htpasswd
  Require valid-user
</Location>
```
Try to put the above config to your httpd.conf or /etc/httpd/conf.d/xxxx.conf.

**Comment by wtakase** [comment]
And restart your httpd service.

**Comment by folderman** [comment]
Hi wtakase,

Can you tell what apache version you are using?

Mine has only /etc/apache2.

testing /etc/apache2 # tree -L 1
.
├── apache2.conf
├── conf-available
├── conf-enabled
├── envvars
├── magic
├── mods-available
├── mods-enabled
├── ports.conf
├── sites-available
└── sites-enabled

**Comment by wtakase** [comment]
My OS is CentOS 7 and apache 2.4.x.
You may add the config to apache2.conf.

**Comment by folderman** [comment]
Hi wtakase,

Below is my configurations:

apache.conf
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf

RewriteEngine on

RewriteRule  ^/?(.*)$ http://localhost:5601/$1 [L,P]
RequestHeader set X-Proxy-User %{REMOTE_USER}e
<Location />
  AuthType Basic
  AuthName "Basic Authentication"
  AuthUserFile /var/www/html/.htpasswd
  Require valid-user
</Location>


</VirtualHost>


Kibana.yml:

xpack.spaces.enabled: false
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: false
own_home.local.groups: [ common01, common02 ]

I have defined 2 users in .htpasswd, when I login with user1, I have found that the index ".kibana_(null)" is created in elasticsearch. Then I do some visualization import. Then quit.

Then I use user2 to login, it seems that it uses .kibana_(null) also as I can see the visualization I imported before.

What I guest is the x-proxy-user is not able to be handled.

I would like to ask whether the below attributes should be set or leave it as default?

own_home.remote_user: '' <-- specify how to fetch username (session, header, or authorization)
own_home.get_username_from_session.enabled: false
own_home.get_username_from_session.key: username

Thanks a lot!

Kenneth

**Comment by folderman** [comment]
After using the setting from:

https://github.com/wtakase/kibana-own-home/issues/67

I am able to get the x-proxy-user attribute:

{"type":"response","@timestamp":"2018-12-19T14:04:20Z","tags":[],"pid":6336,"method":"get","statusCode":304,"req":{"url":"/ui/fonts/open_sans/open_sans_v15_latin_700.woff2","method":"get","headers":{"host":"localhost:5601","origin":"http://10.0.200.103","if-none-match":"\"5a6a45d6f98752b11ccb7c4f0f6fd7faf18ad1a7\"","if-modified-since":"Fri, 09 Nov 2018 19:04:17 GMT","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","accept":"*/*","referer":"http://10.0.200.103/app/monitoring","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7","x-proxy-user":"user2","x-forwarded-for":"10.0.10.103","x-forwarded-host":"10.0.200.103","x-forwarded-server":"#####","connection":"close"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.0.200.103/app/monitoring"},"res":{"statusCode":304,"responseTime":1,"contentLength":9},"message":"GET /ui/fonts/open_sans/open_sans_v15_latin_700.woff2 304 1ms - 9.0B"}

"x-proxy-user":"user2

However, when I login, the own home tag shows (Only shows the text, it doesn't show the colorful interface):

Multi-tenancy for Kibana
Select tenant (kibana.index)
You can switch a tenant (kibana.index) for personal or group use.
Created objects are saved to the selected index.
Your name:
Current tenant (kibana.index): .kibana
Available Tenants
Go back to Top page.


Showing the indices:
It has only .kibana_1, but not .kibana_common01, nor .kibana_common02.

For the .kibana_1, I have further checked, the .kibana_1 was created when I restarted kibana, before I login.

Kenneth

**Comment by folderman** [comment]
Hi All,

Finally changes to CentOS 7, except the reverse proxy setting (please follow thread #67 ).

Other settings work.

I have no idea why using debian 9 wouldnt work.

Kenneth
