### ISSUE TITLE
LDAP Login issue

### ISSUE THREAD

**Issue by ScholesHuang** [wtakase/kibana-own-home#13]
Our LDAP has to login via username and password , and this plugin doesn't have such attributes  : 
own_home.ldap.enabled: false
own_home.ldap.url: ldap://localhost:389
own_home.ldap.userbase: ou=People,dc=localhost
own_home.ldap.rolebase: ou=Groups,dc=localhost
own_home.ldap.search_filter: '(cn=*)'
own_home.ldap.username_attribute: cn
own_home.ldap.rolename_attribute: cn
own_home.ldap.adfs: false

How to resolve this ?

**Comment by wtakase** [comment]
The plugin uses ldapjs module which provides `bind` function:
http://ldapjs.org/client.html#bind

The following files execute LDAP search.
https://github.com/wtakase/kibana-own-home/blob/master/server/fetch_ldap_groups.js
https://github.com/wtakase/kibana-own-home/blob/master/server/validate_by_ldap.js

So I guess we can put `client.bind()` in front of `client.search()`.
And also we can add `own_home.ldap.bind_username`, `own_home.ldap.bind_password` options.

**Comment by wtakase** [comment]
I added the feature.
You can use the following options with own home v5.2.2-1:
```
own_home.ldap.bind.dn
own_home.ldap.bind.password
```
