### ISSUE TITLE
explicit_kibana_index_url" is not allowed in version 6.7.0

### ISSUE THREAD

**Issue by WassimDhib** [wtakase/kibana-own-home#139]
I got this error when installing own_home-6.7.0.zip

> FATAL  ValidationError: child "own_home" fails because ["explicit_kibana_index_url" is not allowed]

Is the explicit_kibana_index_url deprecated ?

**Comment by wtakase** [comment]
The feature was removed from v6.6.0 due to the drastic change for Hapi v17.
I will re-add the feature if I have time.

**Comment by wtakase** [comment]
Re-added the feature.
