### ISSUE TITLE
Elastic Search HTTPS issue

### ISSUE THREAD

**Issue by ScholesHuang** [wtakase/kibana-own-home#15]
Hi Master,
If setting as below :
elasticsearch.url: https://localhost:19200
own_home.elasticsearch.url: https://localhost:9200
Kibanna failed to connect to elastic search .
The question is how to set elastic search https ? Seems it is not intially supported by ES .

**Comment by wtakase** [comment]
Could you give me your kibana.yml?

**Comment by ScholesHuang** [comment]
# Kibana is served by a back end server. This setting specifies the port to use.
#server.port: 5601

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
#server.host: "localhost"

# Enables you to specify a path to mount Kibana at if you are running behind a proxy. This only affects
# the URLs generated by Kibana, your proxy is expected to remove the basePath value before forwarding requests
# to Kibana. This setting cannot end in a slash.
#server.basePath: ""

# The maximum payload size in bytes for incoming server requests.
#server.maxPayloadBytes: 1048576

# The Kibana server's name.  This is used for display purposes.
#server.name: "your-hostname"

# The URL of the Elasticsearch instance to use for all your queries.
#elasticsearch.url: "http://localhost:9200"

# When this setting's value is true Kibana uses the hostname specified in the server.host
# setting. When the value of this setting is false, Kibana uses the hostname of the host
# that connects to this Kibana instance.
#elasticsearch.preserveHost: true

# Kibana uses an index in Elasticsearch to store saved searches, visualizations and
# dashboards. Kibana creates a new index if the index doesn't already exist.
#kibana.index: ".kibana"

# The default application to load.
#kibana.defaultAppId: "discover"

# If your Elasticsearch is protected with basic authentication, these settings provide
# the username and password that the Kibana server uses to perform maintenance on the Kibana
# index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
# is proxied through the Kibana server.
#elasticsearch.username: "user"
#elasticsearch.password: "pass"

# Paths to the PEM-format SSL certificate and SSL key files, respectively. These
# files enable SSL for outgoing requests from the Kibana server to the browser.
#server.ssl.cert: /path/to/your/server.crt
#server.ssl.key: /path/to/your/server.key

# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files validate that your Elasticsearch backend uses the same key files.
#elasticsearch.ssl.cert: /path/to/your/client.crt
#elasticsearch.ssl.key: /path/to/your/client.key

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
#elasticsearch.ssl.ca: /path/to/your/CA.pem

# To disregard the validity of SSL certificates, change this setting's value to false.
#elasticsearch.ssl.verify: true

# Time in milliseconds to wait for Elasticsearch to respond to pings. Defaults to the value of
# the elasticsearch.requestTimeout setting.
#elasticsearch.pingTimeout: 1500

# Time in milliseconds to wait for responses from the back end or Elasticsearch. This value
# must be a positive integer.
#elasticsearch.requestTimeout: 30000

# List of Kibana client-side headers to send to Elasticsearch. To send *no* client-side
# headers, set this value to [] (an empty list).
#elasticsearch.requestHeadersWhitelist: [ authorization ]

# Header names and values that are sent to Elasticsearch. Any custom headers cannot be overwritten
# by client-side headers, regardless of the elasticsearch.requestHeadersWhitelist configuration.
#elasticsearch.customHeaders: {}

# Time in milliseconds for Elasticsearch to wait for responses from shards. Set to 0 to disable.
#elasticsearch.shardTimeout: 0

# Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying.
#elasticsearch.startupTimeout: 5000

# Specifies the path where Kibana creates the process ID file.
#pid.file: /var/run/kibana.pid

# Enables you specify a file where Kibana stores log output.
#logging.dest: stdout

# Set the value of this setting to true to suppress all logging output.
#logging.silent: false

# Set the value of this setting to true to suppress all logging output other than error messages.
#logging.quiet: false

# Set the value of this setting to true to log all events, including system usage information
# and all requests.
#logging.verbose: false
logging.verbose: false

# Set the interval in milliseconds to sample system and process performance
# metrics. Minimum is 100ms. Defaults to 5000.
#ops.interval: 5000

#server.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
#server.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key
elasticsearch.url: https://localhost:9200
#elasticsearch.ssl.ca: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
elasticsearch.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
elasticsearch.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.proxy_user_header: x-proxy-user
own_home.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
own_home.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key
own_home.elasticsearch.url: http://localhost:9200
own_home.elasticsearch.ssl.ca: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.local.groups: [ public, sandbox ]
own_home.ldap.enabled: true
#own_home.ldap.userbase: ou=People,dc=localhost
#own_home.ldap.rolebase: ou=Groups,dc=localhost
own_home.explicit_kibana_index_url.enabled: false
own_home.explicit_kibana_index_url.proxy.url: http://localhost:15601
#own_home.explicit_kibana_index_url.proxy.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
#own_home.explicit_kibana_index_url.proxy.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key

**Comment by ScholesHuang** [comment]
@wtakase 

#Kibana is served by a back end server. This setting specifies the port to use.
#server.port: 5601

#Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
#The default is 'localhost', which usually means remote machines will not be able to connect.
#To allow connections from remote users, set this parameter to a non-loopback address.
#server.host: "localhost"

#Enables you to specify a path to mount Kibana at if you are running behind a proxy. This only affects
#the URLs generated by Kibana, your proxy is expected to remove the basePath value before forwarding requests
#to Kibana. This setting cannot end in a slash.
#server.basePath: ""

#The maximum payload size in bytes for incoming server requests.
#server.maxPayloadBytes: 1048576

#The Kibana server's name.  This is used for display purposes.
#server.name: "your-hostname"

#The URL of the Elasticsearch instance to use for all your queries.
#elasticsearch.url: "http://localhost:9200"

#When this setting's value is true Kibana uses the hostname specified in the server.host
#setting. When the value of this setting is false, Kibana uses the hostname of the host
#that connects to this Kibana instance.
#elasticsearch.preserveHost: true

#Kibana uses an index in Elasticsearch to store saved searches, visualizations and
#dashboards. Kibana creates a new index if the index doesn't already exist.
#kibana.index: ".kibana"

#The default application to load.
#kibana.defaultAppId: "discover"

#If your Elasticsearch is protected with basic authentication, these settings provide
#the username and password that the Kibana server uses to perform maintenance on the Kibana
#index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
#is proxied through the Kibana server.
#elasticsearch.username: "user"
#elasticsearch.password: "pass"

#Paths to the PEM-format SSL certificate and SSL key files, respectively. These
#files enable SSL for outgoing requests from the Kibana server to the browser.
#server.ssl.cert: /path/to/your/server.crt
#server.ssl.key: /path/to/your/server.key

#Optional settings that provide the paths to the PEM-format SSL certificate and key files.
#These files validate that your Elasticsearch backend uses the same key files.
#elasticsearch.ssl.cert: /path/to/your/client.crt
#elasticsearch.ssl.key: /path/to/your/client.key

#Optional setting that enables you to specify a path to the PEM file for the certificate
#authority for your Elasticsearch instance.
#elasticsearch.ssl.ca: /path/to/your/CA.pem

#To disregard the validity of SSL certificates, change this setting's value to false.
#elasticsearch.ssl.verify: true

#Time in milliseconds to wait for Elasticsearch to respond to pings. Defaults to the value of
#the elasticsearch.requestTimeout setting.
#elasticsearch.pingTimeout: 1500

#Time in milliseconds to wait for responses from the back end or Elasticsearch. This value
#must be a positive integer.
#elasticsearch.requestTimeout: 30000

#List of Kibana client-side headers to send to Elasticsearch. To send *no* client-side
#headers, set this value to [] (an empty list).
#elasticsearch.requestHeadersWhitelist: [ authorization ]

#Header names and values that are sent to Elasticsearch. Any custom headers cannot be overwritten
#by client-side headers, regardless of the elasticsearch.requestHeadersWhitelist configuration.
#elasticsearch.customHeaders: {}

#Time in milliseconds for Elasticsearch to wait for responses from shards. Set to 0 to disable.
#elasticsearch.shardTimeout: 0

#Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying.
#elasticsearch.startupTimeout: 5000

#Specifies the path where Kibana creates the process ID file.
#pid.file: /var/run/kibana.pid

#Enables you specify a file where Kibana stores log output.
#logging.dest: stdout

#Set the value of this setting to true to suppress all logging output.
#logging.silent: false

#Set the value of this setting to true to suppress all logging output other than error messages.
#logging.quiet: false

#Set the value of this setting to true to log all events, including system usage information
#and all requests.
#logging.verbose: false
logging.verbose: false

#Set the interval in milliseconds to sample system and process performance
#metrics. Minimum is 100ms. Defaults to 5000.
#ops.interval: 5000

#server.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
#server.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key
elasticsearch.url: https://localhost:9200
#elasticsearch.ssl.ca: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
elasticsearch.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
elasticsearch.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.proxy_user_header: x-proxy-user
own_home.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
own_home.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key
own_home.elasticsearch.url: http://localhost:9200
own_home.elasticsearch.ssl.ca: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.local.groups: [ public, sandbox ]
own_home.ldap.enabled: true
#own_home.ldap.userbase: ou=People,dc=localhost
#own_home.ldap.rolebase: ou=Groups,dc=localhost
own_home.explicit_kibana_index_url.enabled: false
own_home.explicit_kibana_index_url.proxy.url: http://localhost:15601
#own_home.explicit_kibana_index_url.proxy.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
#own_home.explicit_kibana_index_url.proxy.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key

**Comment by wtakase** [comment]
For the first step, let's disable `elasticsearch.ssl.verify`.
What about the following:
```
elasticsearch.url: https://localhost:19200
elasticsearch.ssl.verify: false
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.proxy_user_header: x-proxy-user
own_home.ssl.cert: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.crt
own_home.ssl.key: C:/Scholes/PRD/elk/nginx-1.11.10/nginx-1.11.10/ssl/nginx.key
own_home.elasticsearch.url: https://localhost:9200
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.local.groups: [ public, sandbox ]
```
