### ISSUE TITLE
TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by 20988902** [wtakase/kibana-own-home#2]
**Hi, I add config in my kibana.yml (kibana==5.0.2), like this:**
server.host: "0.0.0.0"
elasticsearch.url: "https://192.168.xx.xx:9200"
elasticsearch.username: "xxxxx"
elasticsearch.password: "xxxxx"
elasticsearch.ssl.ca: '/opt/kibana-5.0.2.sg/config/kirk-signed.pem'
elasticsearch.ssl.verify: false
searchguard.cookie.password: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
own_home.session.secretkey: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
own_home.session.isSecure: false
own_home.local.groups: [ open, reptile ]

**then, I start kibana have the error:**
 log   [14:44:14.905] [info][status][plugin:elasticsearch@5.0.2] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [14:44:14.968] [fatal] TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at fs.readFileSync (fs.js:508:33)
    at module.exports (/opt/kibana-5.0.2.sg/plugins/own_home/server/proxy/init_proxy.js:32:14)
    at ScopedPlugin.init [as externalInit] (/opt/kibana-5.0.2.sg/plugins/own_home/index.js:58:9)
    at ScopedPlugin.tryCatcher (/opt/kibana-5.0.2.sg/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.attempt.Promise.try (/opt/kibana-5.0.2.sg/node_modules/bluebird/js/main/method.js:30:24)
    at /opt/kibana-5.0.2.sg/src/server/plugins/plugin.js:160:44
    at undefined.next (native)
    at step (/opt/kibana-5.0.2.sg/src/server/plugins/plugin.js:11:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by wtakase** [comment]
try:
```
server.host: 0.0.0.0
elasticsearch.url: http://localhost:19200
elasticsearch.username: xxxxx
elasticsearch.password: xxxxx
elasticsearch.ssl.verify: false
searchguard.cookie.password: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
own_home.elasticsearch.url: https://192.168.xx.xx:9200
own_home.elasticsearch.ssl.ca: /opt/kibana-5.0.2.sg/config/kirk-signed.pem
own_home.session.secretkey: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
own_home.session.isSecure: false
own_home.local.groups: [ open, reptile ]
```
or if you want to run this plugin-proxy server with ssl (https://localhost:19200), configure as follows:
```
server.host: 0.0.0.0
elasticsearch.url: https://localhost:19200
elasticsearch.username: xxxxx
elasticsearch.password: xxxxx
elasticsearch.ssl.ca: /path/to/this/proxy/server/cert/CA.crt
elasticsearch.ssl.verify: false
searchguard.cookie.password: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
own_home.ssl.cert: /path/to/this/proxy/server.crt
own_home.ssl.key: /path/to/this/proxy/server.key
own_home.elasticsearch.url: https://192.168.xx.xx:9200
own_home.elasticsearch.ssl.ca: /opt/kibana-5.0.2.sg/config/kirk-signed.pem
own_home.session.secretkey: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
own_home.session.isSecure: false
own_home.local.groups: [ open, reptile ]
```

**Comment by batvanko66** [comment]
Hi, Where do you get the value of this searchguard.cookie.password from?
Thanks

**Comment by wtakase** [comment]
I guess it comes from [this plugin](https://github.com/floragunncom/search-guard-kibana-plugin).

**Comment by batvanko66** [comment]
Thank you. And this oen: own_home.session.secretkey?

**Comment by wtakase** [comment]
That is used for [yar cookieOptions](https://github.com/hapijs/yar#usage).

https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/init_proxy.js#L111

**Comment by batvanko66** [comment]
Thank you.
