### ISSUE TITLE
where is the server with port 19200

### ISSUE THREAD

**Issue by xycloud** [wtakase/kibana-own-home#20]
I do not see any code about 19200, where is it? 
if it should be configured in nginx, could  you please add an official exmaple of server 19200 and 15601

**Comment by wtakase** [comment]
It comes from `elasticsearch.url`:
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/init_proxy.js#L26
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/init_proxy.js#L30
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/init_proxy.js#L58

Actually you can specify any port.

**Comment by xycloud** [comment]
I got below erorr:
```
 [warning][admin][elasticsearch] Unable to revive connection: http://localhost:19200/
```
