### ISSUE TITLE
auth header miss

### ISSUE THREAD

**Issue by xycloud** [wtakase/kibana-own-home#24]
it seems that '/.kibana/index-pattern/_search' miss the request auth header when I use kibana-own-home

**Comment by wtakase** [comment]
What does `the request auth header` mean? `authorization` header?

And could you show me your kibana.yml?

**Comment by xycloud** [comment]
yes which means 'authorization':

kibana version: 5.2.0
I use nginx as a proxy of kibana
I use searchguard

```
elasticsearch.tribe.url: "https://xxxxx.yaaaaaa:443"
elasticsearch.tribe.username: "kibanaserver"
elasticsearch.tribe.password: "xxxxxyyyyyy"

own_home.enabled: true
server.defaultRoute: /app/own_home
elasticsearch.url: http://127.0.0.1:19200
elasticsearch.username: "kibanaserver"
elasticsearch.password: "xxxxxyyyyyy"
elasticsearch.ssl.verify: false
elasticsearch.requestHeadersWhitelist: [ cookie, authorization ]

own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: login
own_home.session.isSecure: false
own_home.elasticsearch.url: http://xxx.yyy:80
own_home.local.groups: [ public, sandbox ]
own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by wtakase** [comment]
If you use nginx and a user is authenticated at the nginx, you can configure nginx like [this.](https://github.com/wtakase/kibana-own-home/issues/14)
And set `elasticsearch.requestHeadersWhitelist: [ cookie, x-proxy-user ]` and `own_home.get_username_from_session.enabled: false`.

If you  use `own_home.get_username_from_session` options, you don't need to use nginx. But you need to set up a Kibana plugin which authenticates users and set username to session like Search Guard Kibana plugin.
And the Search Guard Kibana plugin generates `authorization` header.
https://github.com/wtakase/kibana-own-home#extract-username-from-session-instead-of-request-header-experimental
