### ISSUE TITLE
config for setting the default kibana index

### ISSUE THREAD

**Issue by xycloud** [wtakase/kibana-own-home#26]
[suggestion]: do you mind providing a config for setting the default kibana index

cause i wanna make the kibana_public as the default kibana index if user do not select their own index namespace

**Comment by wtakase** [comment]
I created a [branch.](https://github.com/wtakase/kibana-own-home/tree/defualt-kibana-index-option)
You can set default kibana index as follows:
```
own_home.default_kibana_index_suffix: public
```

There is a problem that the option doesn't work with a LDAP group.
