### ISSUE TITLE
URL not working with ownhome

### ISSUE THREAD

**Issue by nikunjsv** [wtakase/kibana-own-home#31]
kibana  5.3.0
logstash 5.3.0
elasticsearch 5.3.0

when i access http://localhost/app/own_home
i see the tenants:-

Personal tenant
.kibana_kibanaadmin
Shared tenants
.kibana_common01
.kibana_common02

After clilcking the .kibana_kibanaadmin tenant, when i click TOP link (http://localhost/kibanaadmin/app/kibana) it says 
**## {"statusCode":404,"error":"Not Found"}**

Below are my configurations:

- /etc/nginx/conf.d/kibana.conf

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://localhost:5601;
        auth_basic_user_file /etc/nginx/htpasswd.users;
        proxy_set_header Host $host;
        auth_basic "Basic Auth";
        proxy_set_header X-PROXY-USER $remote_user;
    }
}

- /etc/kibana/kibana.yml

elasticsearch.url: "http://localhost:19200"

elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.session.secretkey: tbCbp5CVk7rwUJtpdF8VzNV5xtTBbvMD
own_home.session.isSecure: false
own_home.local.groups: [ common01, common02 ]

own_home.get_username_from_session.enabled: false
own_home.get_username_from_session.key: username
own_home.explicit_kibana_index_url.enabled: true

- /etc/nginx/htpasswd.users

kibanaadmin:n99kBofF.psQ.

**Is this a issue in ownhome or some configuaration issue ?**

**Comment by wtakase** [comment]
try to replace:
```
proxy_pass http://localhost:5601;
```
with
```
proxy_pass http://localhost:15601;
```

**Comment by nikunjsv** [comment]
Thanks @wtakase for your prompt response.

After doing above changes, when i click top link in ownhome it worked.

The URL changes to - 
http://localhost/kibanaadmin/app/kibana#/discover?_g=()&_a=(columns:!(_source)......

But from there when i navigate to visualization or dashboard, URL changes back to normal. It doesnt contain username anymore.

The URL changes - 
http://localhost/app/kibana#/dashboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),....

**Comment by wtakase** [comment]
What about clear the browser cache?
