### ISSUE TITLE
Do you have own home version for kibana 5.3.1?

### ISSUE THREAD

**Issue by anakeen99** [wtakase/kibana-own-home#32]
Because, When i type sudo bin/kibana-plugin install https://github.com/wtakase/kibana-own-home/releases/download/v5.3.0-2/own_home-5.3.0-2.zip and it said Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [own_home]. Expected [5.3.1]; found [5.3.0]".

**Comment by wtakase** [comment]
[Released](https://github.com/wtakase/kibana-own-home/tree/v5.3.1).
