### ISSUE TITLE
version v5.2.2-1 can't change tenant from personal to shared

### ISSUE THREAD

**Issue by waseem-presenso** [wtakase/kibana-own-home#34]
Good day, 

I'm working with ELK version 5.2.2  and own home version v5.2.2-1. I face a problem that I'm not able to change the current tenant to Shared one, I click on the shared tenant it changes for very short time and then change back to the personal tenant.

Relevant configuration:

elasticsearch.url: "http://10.10.0.5:19200"
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.proxy_user_header: x-proxy-user
own_home.elasticsearch.url: "http://10.10.0.52:9200"
own_home.session.secretkey: XXXXXXXXXX
own_home.session.isSecure: true
own_home.session.timeout: 3600000
own_home.local.enabled: true
own_home.local.groups: [ common ]
own_home.explicit_kibana_index_url.enabled: false
own_home.explicit_kibana_index_url.proxy.url: "http://10.10.0.5:15601"

Thanks in advance

**Comment by rbagul** [comment]
Hi Waseem,
Are you using it with X-Pack?

**Comment by wtakase** [comment]
Try to replace `own_home.session.isSecure: true` with `own_home.session.isSecure: false`.

**Comment by waseem-presenso** [comment]
After this change, it works properly.
But why it doesn't work with a secured session?

Thank you.

**Comment by wtakase** [comment]
Own home uses [yar plugin.](https://github.com/hapijs/yar)
In the plugin, `isSecure: true` is allowed only in the case of using https.
https://github.com/hapijs/yar#issecure

**Comment by waseem-presenso** [comment]
I see, thanks for your help
