### ISSUE TITLE
 default_kibana_index_suffix is no effective if we clean the cookie

### ISSUE THREAD

**Issue by Zuckonit** [wtakase/kibana-own-home#35]
question: default_kibana_index_suffix is no effective if we clean the cookie
steps:
```
    1. select public as the kibana index
    2. clean cookie
    3. refresh
```
version: kibana 5.2.0
config:
```
kibana.yml:
server.defaultRoute: /app/kibana
own_home.default_kibana_index_suffix: public
...
```

**Comment by wtakase** [comment]
After the refreshing, what was set as kibana.index?

**Comment by Zuckonit** [comment]
undefined

**Comment by wtakase** [comment]
`default_kibana_index_suffix` is supported from v5.3.1.

**Comment by Zuckonit** [comment]
i do change the own_home's package version to 5.2.0

**Comment by wtakase** [comment]
I tried with v5.4.0 and I cannot reproduce it.
![default_kibana_index](https://cloud.githubusercontent.com/assets/8382795/25977902/d7ba23b8-36f9-11e7-90a9-ee6c2cde7bfc.gif)

My kibana.yml as follows:
```
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
server.defaultRoute: /app/kibana
own_home.default_kibana_index_suffix: public
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: false
```

**Comment by Zuckonit** [comment]
clear the cache， then directly open home page http://localhost:8080

**Comment by wtakase** [comment]
Result is the same.
![default_kibana_index](https://cloud.githubusercontent.com/assets/8382795/25978300/58fe7562-36fc-11e7-99a2-e617b9950cde.gif)
