### ISSUE TITLE
LDAP login

### ISSUE THREAD

**Issue by rbagul** [wtakase/kibana-own-home#36]
Hi Wtakase,

Thank you for writing this plugin. I have been trying to set it up with LDAP authentication, However It is not asking for any login option. Kibana loads at localhost:80 without login. 
We are using Apache 2.4, Kibana-5.2.2, ES-5.2.2 and Kibana-own-home-5.2.2-1.

Apache httpd configuration is:
<VirtualHost *:80>
  ServerName kibana
  RewriteEngine On
  RewriteRule  ^/?(.*)$ http://localhost:5601/$1 [L,P]
  <Location />
    # Bypass auth for load balancer API / health check of kibana service
    SetEnvIf Request_URI "/api/status.*" STATUS_noauth=1
    # All others require LDAP auth
    AuthLDAPBindDN "CN=svc.xxxx,OU=ServiceAccounts,OU=Process,DC=ads,DC=xxxx,DC=com"
    AuthLDAPBindPassword “xxxxx”
    AuthLDAPURL "ldap url”
    AuthType Basic
    AuthName "LDAP Login"
    AuthBasicProvider ldap
    AuthUserFile /dev/null
    require valid-user
    Satisfy any
    Require all denied
    Allow from 127.0.0.1
    Allow from env=STATUS_noauth
  </Location>
  <Proxy *>
    Require all granted
    RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
    RequestHeader set X-Proxy-User "%{PROXY_USER}e"
   </Proxy>
  </VirtualHost>

Kibana.yml configuration is:
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.elasticsearch.url: http://localhost:9200
own_home.session.isSecure: false
own_home.local.groups: [ public, sandbox ]
own_home.local.enabled: false
own_home.ldap.enabled: true
own_home.ldap.url: ldap://ldapurl
own_home.ldap.bind.dn: CN=svc.xxxx,OU=ServiceAccounts,OU=Process,DC=ads,DC=xxxxx,DC=com
own_home.ldap.bind.password: xxxxxx
own_home.ldap.search_filter: '(cn=*)'
own_home.ldap.username_attribute: cn
own_home.ldap.rolename_attribute: cn

Your guidance is much appreciated. 

Thanks,
Rakesh

**Comment by wtakase** [comment]
First of all, does your apache LDAP authentication works without Own home?

**Comment by rbagul** [comment]
You are right. After fixing apache LDAP authentication, it works fine. 
Is there any chance you would modify this plugin for x-pack. 

Thank you so much!
Rakesh

**Comment by wtakase** [comment]
> Is there any chance you would modify this plugin for x-pack.

I don't have x-pack license.
