### ISSUE TITLE
Debug Help: Port is already in use

### ISSUE THREAD

**Issue by mrsatishkumar** [wtakase/kibana-own-home#37]
Hi
I'm trying own_home without searchguard by overriding getRemoteUser to give some default values. but when I install the plugin and run kibana I get an error saying "127.0.0.1:9200 is already in use" which is elastic search address.
Can you please suggest me what I'm missing.

**Comment by mrsatishkumar** [comment]
I missed elasticsearch.url configuration. I resolved this issue.

**Comment by jaleeshacker** [comment]
@mrsatishkumar Can you please guide me how you resolved this issue ? What sort of configuration you applied to fix this. My exact error is 

 _

> error  [13:52:18.379] [error][plugin:own-home] Error: listen EADDRINUSE: address already in use 127.0.0.1:9200
>     at Server.setupListenHandle [as _listen2] (net.js:1277:14)
>     at listenInCluster (net.js:1325:12)
>     at GetAddrInfoReqWrap.doListen (net.js:1458:7)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)

_

**Comment by wtakase** [comment]
Could you show me your Kibana version and `kibana.yml`?

**Comment by jaleeshacker** [comment]
> Could you show me your Kibana version and `kibana.yml`?

Hi wtakase, 

Thanks for your response mate.
I followed the instruction you provided once again from the start and the error disappeared. 
thanks heaps mate.
