### ISSUE TITLE
[fatal] Error: Invalid proxy handler options

### ISSUE THREAD

**Issue by yangbaida** [wtakase/kibana-own-home#39]
[fatal] Error: Invalid proxy handler options (/{paths*}) {
  "agent": {
    "domain": null,
    "_events": {},
    "_eventsCount": 1,
    "defaultPort": 80,
    "protocol": "http:",
    "options": {
      "path": null
    },
    "requests": {},
    "sockets": {},
    "freeSockets": {},
    "keepAliveMsecs": 1000,
    "keepAlive": false,
    "maxSockets": null,
    "maxFreeSockets": 256
  },
  "xforward": true,
  "passThrough": true,
  "timeout": 30000
}

[1] "modifyPayload" is not allowed

In the kibana-own-home-5.4.0/server/proxy/init_proxy.js line 77
 modifyPayload: modifyPayload(kbnServer),

the payload should be decalred and assigned by modifyPayload(kbnServer) before
Wreck.read(response, { json: true }, function (err, payload)

So I change it into payload =  modifyPayload(kbnServer), and move it to line 83, then the plugin runs well.

**Comment by wtakase** [comment]
I cannot reproduce `[1] "modifyPayload" is not allowed` in my environment.
Could you give me more information how to reproduce it?
