### ISSUE TITLE
Failed to replace the string in commons.bundle.js

### ISSUE THREAD

**Issue by turbotoni** [wtakase/kibana-own-home#41]
Hi there,
first of all, very nice plugin dude!

But since the Kibana 5.4 version we have a problem with OwnHome:
We are currently using the "explicit kibana.index in URL feature" with the following configuration:

elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.session.secretkey: ***
own_home.local.groups: [ shared ]
own_home.session.isSecure: true
own_home.explicit_kibana_index_url.enabled: true
elasticsearch.url: "http://***:19200"
own_home.elasticsearch.url: http://***:9200

And of course:

RewriteEngine on
RewriteRule  ^/?(.*)$ http://localhost:15601/$1 [L,P]

at our httpd configuration.

If this feature is disabled the plugin works perfectly.
But if we enable this everytime someone access the Kibana interface the Log says:

[warning][plugin:own-home] Failed to replace the string in commons.bundle.js: "app/kibana" => "USER/app/kibana"

Any plan what we've made wrong?

Greetings,
Toni

**Comment by wtakase** [comment]
What about the [patch?](https://github.com/wtakase/kibana-own-home/commit/eafe7f29539f5fe1c0cbce79e34bcfd6dac8d8ce)

**Comment by turbotoni** [comment]
Thank you! Your fix works perfectly!
