### ISSUE TITLE
session.user as default kibana index

### ISSUE THREAD

**Issue by xycloud** [wtakase/kibana-own-home#42]
how to set session.user as default kibana.index

**Comment by wtakase** [comment]
could you provide more information such as your use case, kibana.yml?

**Comment by xycloud** [comment]
i wanna provide only a private namespace for each user. that means no 'public' and no 'sandbox'

**Comment by wtakase** [comment]
If you don't set `own_home.default_kibana_index_suffix`, by default, remoteUser (username) is used as default kibana index suffix: 
https://github.com/wtakase/kibana-own-home/blob/master/server/get_kibana_index.js#L10
