### ISSUE TITLE
Unable to pass x-proxy-user to kibana own home

### ISSUE THREAD

**Issue by bannewng** [wtakase/kibana-own-home#43]
It's seems I am unable to pass the x-proxy users to kibana own home.
![screen shot 2017-05-17 at 3 44 04 pm](https://cloud.githubusercontent.com/assets/14172209/26143519/e7d36f26-3b17-11e7-8fed-1f25dbba8bd8.png)

Setting in nginx conf.d
```
   location /somewhere {
	
	auth_basic "Authentication";
	auth_basic_user_file /../../htpasswd-path;
        proxy_pass http://localhost:5601/;
        proxy_set_header X-PROXY-USER $remote_user;
	
         #tried to added / not added 
        # proxy_set_header Host $host;

 }

```

Setting in kibana.yml

```
elasticsearch.url: "http://localhost:19200"

elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]

own_home.proxy_user_header: x-proxy-user
own_home.session.secretkey: a-32-characters-long-password
own_home.session.isSecure: false
own_home.local.groups: [ common01, common02 ]

```

I have couples of question, first, i don't understand the usage for own_home.session.secretkey.. 
and is $remote_user in X-PROXY-USER just a random name?..

I am new to it, thank you!.

**Comment by wtakase** [comment]
Could you tell me your kibana version?

About nginx configuration, I hope [this](https://github.com/wtakase/kibana-own-home/issues/14#issuecomment-289352809) helps you, but it seems that there is not much difference.

After the basic authentication, authenticated username is set to $remote_user.
And then, nginx sends the username to Kibana by using `X-PROXY-USER` header. 

Own home uses  `yar` module for session management.
`own_home.session.secretkey` is used for cookie encryption:
https://github.com/hapijs/yar#usage

**Comment by wtakase** [comment]
One more thing, length of `own_home.session.secretKey` must be at least 32 characters long.

**Comment by bannewng** [comment]
I am using Elasticsearch 5.1.2 and kibana own home branch 5.1
and confirmed my password is at least 32 characters long..

**Comment by bannewng** [comment]
It's working for kibana 5.4 with same setting!
Seems related to some other issue. Thanks anyway!

**Comment by wtakase** [comment]
I checked with v5.1.2 and it seems to work.

nginx.conf
```
. . .
location / {
  auth_basic "Basic Auth";
  auth_basic_user_file /path/to/.htpasswd;
  proxy_set_header X-PROXY-USER $remote_user;
  proxy_pass http://localhost:5601;
}
. . .
```

kibana.yml
```
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: false
```

**Comment by bannewng** [comment]
It seems related to my nginx setting.
I use a white list to allow what can be passed to the server, and I have the following location added to the white list and seems still not okay.

```
    location app/own_home# {
    	proxy_pass http://127.0.0.1:5601/app/own_home#;
. .
. .
. .
    }
```

any idea about what I should also include in the whitelist.. ? thanks

**Comment by wtakase** [comment]
sorry, I'm not a nginx expert and I have no experience of using own home with a white list.
