### ISSUE TITLE
Unable to connect to Elasticsearch at http://localhost:19200

### ISSUE THREAD

**Issue by Muhammad-Ezzat** [wtakase/kibana-own-home#45]
**I configured Nginx Reverse proxy with this configurations:**

>  location /  {
> 	 proxy_pass http://localhost:5601;
>     	 auth_basic "Protected Kibana";
>     	 auth_basic_user_file /etc/nginx/.htpasswd;
>          proxy_redirect off;
>     }

and it works fine for authenticating by username and password to access kibana 

**Now, own home plugin configuration is:**

> elasticsearch.url: http://localhost:19200
> elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
> own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
> own_home.session.isSecure: false
> own_home.local.groups: [ common01, common02 ]
 
**When I start kibana I get these errors:**

>   log   [11:37:10.670] [error][admin][elasticsearch] Request error, retrying
> HEAD http://localhost:19200/ => connect ECONNREFUSED 127.0.0.1:19200
  
> log   [11:37:10.857] [error][status][plugin:elasticsearch@5.4.1] Status changed from yellow to red - Unable to connect to Elasticsearch at http://localhost:19200.

**And Here's something strange**
when I use curl localhost:19200 I get the normal elasticsearch response but when I try to access request localhost:19200 from the browser or the postman I get an empty body.

**In the end**
kibana works fine but without the own home multi tenancy functionality as this is what I get from accessing the own home section:

> Your name: 
> Current tenant (kibana.index): .kibana

An empty user name and the default kibana index as my current index.

**Comment by wtakase** [comment]
Add the following line to your nginx conf:
```
proxy_set_header X-PROXY-USER $remote_user;
```
See: https://github.com/wtakase/kibana-own-home/issues/14#issuecomment-289352809

**Comment by Muhammad-Ezzat** [comment]
Thank you @wtakase, now the own home multi tenancy functionality is working properly. However I still have the same error messages when I start kibana can you please explain why I get those messages.

**Comment by wtakase** [comment]
When kibana service starts, elasticsearch plugin is loaded and the plugin tries to connect `localhost:19200`.
But at this time, own home plugin haven't loaded yet, so elasticsearch plugin reports `ECONNREFUSED` error message.
After own home plugin loaded, elasticsearch plugin may become to able to connect `localhost:19200`.
```
. . .
server    log   [06:41:45.674] [info][status][plugin:elasticsearch@5.4.1] Status changed from uninitialized to yellow - Waiting for Elasticsearch
server    log   [06:41:46.583] [error][admin][elasticsearch] Request error, retrying
HEAD http://localhost:19200/ => connect ECONNREFUSED 127.0.0.1:19200
server    log   [06:41:46.585] [info][status][plugin:own_home@5.4.1] Status changed from uninitialized to green - Ready
server    log   [06:41:46.599] [info][plugin:own-home] Proxy server started at http://localhost:19200
. . .
```

**Comment by Muhammad-Ezzat** [comment]
Thank you so much, @wtakase.
