### ISSUE TITLE
Own Home with ReadOnlyREST

### ISSUE THREAD

**Issue by shubhamverma27** [wtakase/kibana-own-home#47]
How to use this plugin with readonlyrest security.
I tried installing it with settings similar to searchguard settings as given. But It works only when logged in with admin access .
With other users ..it gives timed out error on clicking discover tab!!

**Comment by shubhamverma27** [comment]
Hi, I confiugred it using help from previous issues.But now I am not able to create any index patterns in any account!!
Dont even have the default index pattern..help @wtakase @arslanm

**Comment by wtakase** [comment]
Could you share me your configuration (such httpd.conf, kibana.yml, elasticsearch.yml)?
Example is found in #18.

**Comment by shubhamverma27** [comment]
Never Mind.. readonly was blocking access to .kibana for own home .. I added an exception.

@wtakase My Use case allow a user to create dashboards and then share them with his team ..how to implement it using own home?

**Comment by wtakase** [comment]
create a LDAP group such `group01` and share `.kibana_group01` index among the group.
Then on readonlyrest side, set ACL that one of the users belonging to the group can read/write the index to create dashboards, and the others belonging to the group only read the index.

**Comment by shubhamverma27** [comment]
and how do i create this group index in own home? is it similar to
kibana_sandbox index?

**Comment by wtakase** [comment]
Set up your LDAP service and configure own home with the LDAP (see [this example](https://github.com/wtakase/kibana-own-home#configuration-with-ldap)).
If `user01` belongs to LDAP group `group01`, own home fetches the group name and creates `.kibana_group01` kibana.index automatically.

**Comment by shubhamverma27** [comment]
@wtakase So by this method, would the user have to change his index on every kibana login? ie through the own home ui 
like kibana_user is default then change it to kibana_group?

**Comment by shubhamverma27** [comment]
@wtakase How to configure LDAP i Added the given settings to kibana.yml :-

server.defaultRoute: /app/own_home
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ cookie, authorization ]
elasticsearch.username: kibana
elasticsearch.password: kibana
#elasticsearch.ssl.verify: false
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.elasticsearch.url: http://localhost:9200
own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#searchguard.cookie.secure: false
#searchguard.cookie.password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
own_home.local.groups: [ public ]
own_home.local.enabled: false
own_home.ldap.enabled: true
own_home.ldap.url: ldap://xx
own_home.ldap.bind.dn: cn=xxxx,OU=xxxI,DC=xx,DC=com
own_home.ldap.bind.password: xxxx
own_home.ldap.userbase: DC=edelcap,DC=com
own_home.ldap.rolebase: ou=Groups,DC=xxxx,DC=com
own_home.ldap.search_filter: '(cn=*)'
own_home.ldap.username_attribute: sAMAccountName
own_home.ldap.rolename_attribute: cn



i am Not using any httpd settings/proxy!!
What Am i Doing wrong here

**Comment by shubhamverma27** [comment]
log   [07:54:09.523] [error][implementation][internal] Error: read ECONNR                 ESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26)
Debug: internal, implementation, error
    Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26)


logs from kibana.yml

**Comment by shubhamverma27** [comment]
@wtakase  any help is really appreciated here ...
I am currently really stuck at this point :/

**Comment by wtakase** [comment]
currently `own_home.get_username_from_session` is only tested with `search-guard-kibana-plugin`.
If you don't use the search-guard plugin, you need to set up proxy server in front of kibana.

**Comment by shubhamverma27** [comment]
The Session thing is working properly and i am able to create per user kibana.index but I am not able to connect the LDAP groups :/ @wtakase

**Comment by shubhamverma27** [comment]
@wtakase any help regarding LDAP?

**Comment by wtakase** [comment]
OK. The prblem seems LDAP configuration.
On your terminal, let's exec the following simple ldapsearch command:
`ldapsearch -H ldap://xx -LLL -x -b "ou=Groups,DC=xxxx,DC=com"` 

What kind of response do you get?

**Comment by shubhamverma27** [comment]
ldaps:
    
    - name: ldap1
      host: "xxxx.com"
      port: 389        
      ssl_enabled: false                                        # default true
      ssl_trust_all_certs: true                                 # default false
      bind_dn: "cn=xx,OU=Generic IDs,DC=xxx,DC=com"                     # skip for anonymous bind
      bind_password: "xxxx"                                 # skip for anonymous bind
      search_user_base_DN: "DC=xxxx,DC=com"
      user_id_attribute: "sAMAccountName"                                  # default "uid"
      search_groups_base_DN: "OU=Groups,DC=edelcap,DC=com"
      unique_member_attribute: "member"                   # default "uniqueMember"
      connection_pool_size: 30                                  # default 30
      connection_timeout_in_sec: 100                             # default 1
      request_timeout_in_sec: 100                                # default 1
      cache_ttl_in_sec: 60                                      # default 0 - cache disabled
      
      

Here are My LDAP settings from readonlyrest which works properly..
I dont have ldapsearch in terminal
Please refer this


Also, What currently is happening is that any user is getting into kibana without authetication and .kibana _ abcdanyuser is being made

**Comment by wtakase** [comment]
First of all, is there `abcdanyuser` user in your LDAP?

And could you try to replace `own_home.ldap.username_attribute: sAMAccountName` with `own_home.ldap.username_attribute: cn`?

**Comment by shubhamverma27** [comment]
no that user is not there @wtakase 
still the same error..
any random userid is getting autheticated

**Comment by shubhamverma27** [comment]
server.defaultRoute: /app/own_home
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [cookie, authorization ]
elasticsearch.username: kibana
elasticsearch.password: kibana
elasticsearch.ssl.verify: false
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.elasticsearch.url: http://localhost:9200
own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#searchguard.cookie.secure: false
#searchguard.cookie.password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
own_home.local.groups: [ public ]
own_home.local.enabled: false
own_home.ldap.enabled: true
own_home.ldap.url: ldap://gc.edelcap.com:389
own_home.ldap.bind.dn: 'CN=BSG Auth,OU=Generic IDs,DC=edelcap,DC=com'
own_home.ldap.bind.password: 'edelcap2005'
own_home.ldap.userbase: 'DC=edelcap,DC=com'
own_home.ldap.rolebase: 'ou=Groups,DC=edelcap,DC=com'
own_home.ldap.search_filter: '(cn=*)'
own_home.ldap.username_attribute: cn
own_home.ldap.rolename_attribute: cn
own_home.ldap.adfs: true

**Comment by shubhamverma27** [comment]
server.defaultRoute: /app/own_home
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [cookie, authorization ]
elasticsearch.username: kibana
elasticsearch.password: kibana
elasticsearch.ssl.verify: false
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.elasticsearch.url: http://localhost:9200
own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#searchguard.cookie.secure: false
#searchguard.cookie.password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
own_home.local.groups: [ public ]
own_home.local.enabled: false
own_home.ldap.enabled: true
own_home.ldap.url: ldap://xx.xxxx.com:389
own_home.ldap.bind.dn: 'CN=xxxx,OU=Generic IDs,DC=xxx,DC=com'
own_home.ldap.bind.password: 'xxxx'
own_home.ldap.userbase: 'DC=xxx,DC=com'
own_home.ldap.rolebase: 'ou=Groups,DC=xxx,DC=com'
own_home.ldap.search_filter: '(cn=*)'
own_home.ldap.username_attribute: cn
own_home.ldap.rolename_attribute: cn
own_home.ldap.adfs: true

**Comment by wtakase** [comment]
In your situation, all users are recognized as `abcdanyuser` by own home plugin, right?
Then, own home tries to fetch LDAP groups that `abcdanyuser` belongs to.
So it's necessary to exist `abcdanyuser` in your LDAP.

**Comment by shubhamverma27** [comment]
@wtakase What i am trying to say that 
even if I login with a LDAP defined user , It doesn't show any Groups
and If I put in any random User Id then It also Logins (Both are separate issues).
In readonlylogs , Its not authenticated/authorised but due to ownhome settings it logs onto .kibana_xyz index

**Comment by shubhamverma27** [comment]
[2017-07-06T12:32:16,204][INFO ][o.e.c.m.MetaDataCreateIndexService] [IHb1r-c] [.kibana_bsgdassda] creating index, cause [api], templates [], shards [1]/[1], mappings [server, config]

log from es... It creates a index based on whatever id i mention without ldap authentication

**Comment by shubhamverma27** [comment]
Is there any debug mdoe for own home plugin @wtakase

**Comment by wtakase** [comment]
1. about any random userid is getting autheticated
own home doesn't do any authentication.
authentication is done by proxy server or search-guard-kibana-plugin.

2. about fetching LDAP groups
Instead of `ldapsearch`, is there any way or tool to fetch LDAP group list from your LDAP?

3. about debug mode
You can get more message by adding `logging.verbose: true` to your kibana.yml.

**Comment by shubhamverma27** [comment]
@wtakase 
Yes , I have LDAP ADMIN and Also, The Above Given readonlyrest ldap settings is successfully fetching the LDAP groups and that is working fine ..
about authetication, I ll find a way around that once I fetch the groups succesfully  :confounded:

**Comment by shubhamverma27** [comment]
@wtakase any suggestions...?

**Comment by shubhamverma27** [comment]
This isn't working even without LDAP ...I guess Picking Up user from session doesn't work with readonly.

**Comment by wtakase** [comment]
> This isn't working even without LDAP ...I guess Picking Up user from session doesn't work with readonly.

I only tested with httpd proxy, own home, and readonlyrest with `proxy_auth`.

About LDAP issue, how about your LDAP log and own home log with debug mode?

**Comment by shubhamverma27** [comment]
@wtakase Nevermind,  I am using multiple kibana instances per group now ..
The Plugin isn't fully compatible with readonlyrest currently :)

**Comment by seanziee** [comment]
Just for reference, using nginx, ownhome and readonlyrest works fine for me.
