### ISSUE TITLE
Username with '@' sign

### ISSUE THREAD

**Issue by macpoint** [wtakase/kibana-own-home#52]
Hi, 
my http server sets `x-auth-token` with username in e-mail address format (user@company.com). When I select a public tenant (for example `.kibana_public`) and re-select back the user-owned tenant (.kibana_user@company.com), current index does not get switched and the `.kibana_public` is still in use. If I change my web server settings to avoid setting the header with '@', everything works ok.

Can this be fixed?

Thanks

**Comment by wtakase** [comment]
[This patch](https://github.com/wtakase/kibana-own-home/commit/f9c26e29cf9008523d88e6f61233cdef3ba689ec) fix it.

**Comment by macpoint** [comment]
Thanks, the patch works fine.
