### ISSUE TITLE
LDAP search filter

### ISSUE THREAD

**Issue by macpoint** [wtakase/kibana-own-home#53]
Hi,

in `/server/ldap/get_ldap_config.js` you use this search filter

`filter: '(&' + searchFilter + '(member' + adfsNested + '=' + usernameAttribute + '=' + remoteUser + ',' + userbase + '))',`

my LDAP server does not expect the `member` parameter, but rather `uniquemember`. Moreover, not all users are part of the same DN - i. e. some users are in `l=emea,dc=company,dc=com`, some others are in  `l=amer,dc=company,dc=com`, etc ... This makes the `+ userbase` unusable as there are potentially multiple different user bases... It would be better to construct the search filter based on the complete DN of the actual user.

Thanks

**Comment by wtakase** [comment]
Thanks for your report.

> my LDAP server does not expect the member parameter, but rather uniquemember. 

I will improve the plugin to support it.


> Moreover, not all users are part of the same DN - i. e. some users are in l=emea,dc=company,dc=com, some others are in l=amer,dc=company,dc=com, etc ... This makes the + userbase unusable as there are potentially multiple different user bases... It would be better to construct the search filter based on the complete DN of the actual user.

Do you have any ideas to get the complete DN from each username (e.g. `user01`)?
For example, there are two DNs (users), `cn=user01,l=emea,dc=company,dc=com` and `cn=user01,l=amer,dc=company,dc=com`.
In this case how do we decide which DN to use for username `user01`?

Ideas:

* Use DN as a username, or
* http server checks user's DN somehow, then sends `x-proxy-user` and the DN as `x-proxy-user-dn` headers.

**Comment by macpoint** [comment]
> Do you have any ideas to get the complete DN from each username (e.g. user01)?
For example, there are two DNs (users), cn=user01,l=emea,dc=company,dc=com and cn=user01,l=amer,dc=company,dc=com.
In this case how do we decide which DN to use for username user01?

I think that if you provide an attribute that is considered uniq in the LDAP schema (like `uid` or `mail`), you should identify the user. Here are the equivalents for ldapsearch:

`ldapsearch -h ldap.company.com -x -b "dc=company,dc=com" "(&(objectClass=person)(uid=user01))" dn`

`ldapsearch -h ldap.company.com -x -b "dc=company,dc=com" "(&(objectClass=person)(mail=user01@company.com))" dn`

> Use DN as a username, or
http server checks user's DN somehow, then sends x-proxy-user and the DN as x-proxy-user-dn headers.

My http server does not supply user DN in header but it would be sufficient for other users whose http server does that.

**Comment by wtakase** [comment]
ok, by this [patch](https://github.com/wtakase/kibana-own-home/commit/25678c13ac452321169300fcaa1f38808d4e0bed), you can choose member attribute from `member`, `memberUid`, and `uniquemember`.

And if you enable `own_home.ldap.get_dn_by_uid` option, the plugin fetches user's DN by using uid (username), then fetches groups by the DN.

**Comment by macpoint** [comment]
Thanks, it works for me. The only thing which might be worth replacing is the [hardcoded](https://github.com/wtakase/kibana-own-home/blob/master/server/ldap/get_groups.js#L40) `uid` parameter by `username_attribute`.

**Comment by wtakase** [comment]
[Fix it](https://github.com/wtakase/kibana-own-home/commit/06ff08736b464a6ac378de4f219c88d7c681a005).

**Comment by macpoint** [comment]
It works as expected. Thanks for implementing this one. 👍
