### ISSUE TITLE
usage with other plugins

### ISSUE THREAD

**Issue by wonnado** [wtakase/kibana-own-home#58]
Hi, 
I tried to use your plugin with [Kibana Object Format](https://github.com/istresearch/kibana-object-format), but I got an error, when I wanted to go to Own Home page 
`Uncaught Error: [$injector:unpr] Unknown provider: confirmModalPromiseProvider <- confirmModalPromise <- indexPatterns <- courier http://errors.angularjs.org/1.4.7/$injector/unpr?p0=confirmModalPromiseProvider%20%3C-%20confirmModalPromise%20%3C-%20indexPatterns%20%3C-%20courier` and don't have any idea what is the reason.
Can you shed some light on the problem?
Thanks!

**Comment by wtakase** [comment]
Could you provide more information (version, kibana.yml, procedure to reproduce it, etc...) ?
