### ISSUE TITLE
x-pack

### ISSUE THREAD

**Issue by batvanko66** [wtakase/kibana-own-home#6]
Hi,
Can this plugin be implemented when x-pack is already in place?
Thank you.

**Comment by wtakase** [comment]
I have no experience in x-pack. I partly confirmed it works with [Search Guard](https://github.com/floragunncom/search-guard).

**Comment by batvanko66** [comment]
Thank you. In the Instructions part: **Example of httpd configuration with Basic authentication**, you give an apache config. example and my kibana runs with nginx. What would the relevant nginx configuration be or does kibana-own-home plugin installs apache and this is what you are referring to? Sorry for the questions but after installing it today I got 503 Bad Gateway error and could not see where I miss-configured. Thanks

**Comment by wtakase** [comment]
OK, you use nginx as a front end server. There is no problem.
A front end server authenticates a user and proxies the user's request to Kibana with username by using request header `x-proxy-user`.

The example is just an example. You can use nginx and also you can use any authentication instead of Basic authentication.
The important parts are:

- sets request header `x-proxy-user`,
- proxies user's request to Kibana.

I'm not familiar with nginx but, If you give me config files of nginx and kibana.yml, I may help you.

**Comment by batvanko66** [comment]
Thank you. x-pack is a roll based authentication that elastic sells/implements to get to kibana and I wonder if it creates a conflict.  What process listens on 19200 port? When I do wget http://localhost:19200 there is no answer.

**Comment by wtakase** [comment]
All requests to ElasticSearch are intercepted by the process listening on 19200 and the process replaces kibana.index string with user-specified one.
https://github.com/wtakase/kibana-own-home#how-it-works

For example, `curl http://localhost:19200` returns the same JSON output as http://localhost:9200 if your elasticsearch runs on localhost:
```
$ curl http://localhost:19200
{"name":"yeOO8Zl","cluster_name":"elasticsearch","cluster_uuid":"ltmxauN6Rxer5b5I8f8agw","version":{"number":"5.1.2","build_hash":"c8c4c16","build_date":"2017-01-11T20:18:39.146Z","build_snapshot":false,"lucene_version":"6.3.0"},"tagline":"You Know, for Search"}
```
```
$ curl http://localhost:9200
{
  "name" : "yeOO8Zl",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ltmxauN6Rxer5b5I8f8agw",
  "version" : {
    "number" : "5.1.2",
    "build_hash" : "c8c4c16",
    "build_date" : "2017-01-11T20:18:39.146Z",
    "build_snapshot" : false,
    "lucene_version" : "6.3.0"
  },
  "tagline" : "You Know, for Search"
}
```
If you set `x-proxy-user` header then, the process replaces `.kibana` with `.kibana_test01`:
```
$ curl http://localhost:19200/.kibana/_search -H 'x-proxy-user:test01'
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":".kibana_test01","index_uuid":"_na_","index":".kibana_test01"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":".kibana_test01","index_uuid":"_na_","index":".kibana_test01"},"status":404}
```

**Comment by batvanko66** [comment]
Thank you. I will run some tests and let you know.

**Comment by ISMAELMARTINEZ** [comment]
Hi batvanko66. How did it go with the trials? I am thinking about using this great plugging but also got x-pack to integrate it with. Much appreciated

**Comment by batvanko66** [comment]
Hi Ismael, we are currently using only xpack. As per elastic you can do fine-grain RBAC tuning so this is where our current focus is.

**Comment by ISMAELMARTINEZ** [comment]
@batvanko66 , do you "share" all teh visualizations and dashboards or is that possible to filter them by the xpack "filters"??
Thanks a lot!!

**Comment by AlexandrTuniev** [comment]
Hi @batvanko66  , did you manage to get work x-pack and this plugin together  ?

**Comment by batvanko66** [comment]
Hi,
No, we are not going to use it.

**Comment by AlexandrTuniev** [comment]
Tried to combine two plugins x-pack and own-home but seems need some modifications in own-home plugin, getting this error in kibana console 
![untitled](https://cloud.githubusercontent.com/assets/7453199/24046812/479694f2-0b3d-11e7-8044-4326d233223c.png)

Can you please give a hint where in code I should modify so the all unhandled requests will just pass without modifications to elastic? Or maybe some other solution.

**Comment by wtakase** [comment]
I have no experience with x-pack.

This file launches a proxy server and the server proxies all requests from Kibana to Elasticsearch.
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/init_proxy.js

**Comment by Valered** [comment]
Any news about using both x-pack and own-home togheter??
