### ISSUE TITLE
version 6.1.1

### ISSUE THREAD

**Issue by TomasKoutek** [wtakase/kibana-own-home#63]
Hi,
first of all, I would like to thank you for the awesome plugin. I'm dealing with upgrade elasticsearch (+ searchguard, kibana, ...) to version 6.1.1. Do you have any plans to release a supported version?

Thank you
Tomáš

**Comment by numbnut** [comment]
This would be really great to know. If you need any help to get the upgrade done, let me know. I will do my best, to support you.

**Comment by wtakase** [comment]
[Released](https://github.com/wtakase/kibana-own-home/tree/v6.1.1).

**Comment by numbnut** [comment]
Thank you very much!

**Comment by TomasKoutek** [comment]
Wow, thank you very much!
