### ISSUE TITLE
Build script or instructions

### ISSUE THREAD

**Issue by rhabbachi** [wtakase/kibana-own-home#64]
Hi @wtakase, thanks for the great plugin.

Do you have a build script to generate the zip bundle used during `kibana-plugin install`? Or some build instructions.

**Comment by wtakase** [comment]
Here is the instruction:

```
$ git clone https://github.com/elastic/kibana
$ cd kibana/
$ git checkout v5.6.4
$ nvm install `cat .node-version`
$ npm install
$ cd plugins/
$ git clone https://github.com/wtakase/kibana-own-home
$ cd kibana-own-home/
$ git checkout v5.6.4
$ npm install --legacy-bundling
$ npm run build
```

You can find `own_home-5.6.4.zip` under `build/`.

**Comment by rhabbachi** [comment]
Thanks!

I think those instructions are very helpful for anybody that want to
contribute to Own Home. Mind if I submit a PR to add them to the README?

--

*Riadh Habbachi*
*Technical Lead*

E: riadh.habbachi@gmail.com

M: +216 52 693 794

**Comment by wtakase** [comment]
Thanks for the PR!
