### ISSUE TITLE
Overwritting an object

### ISSUE THREAD

**Issue by psaiz** [wtakase/kibana-own-home#7]
Hi again Wataru, 

I'm having issues overwriting visualizations or dashboards.
The first time that I save a visualization, it works properly. If I do some modifications, and save it again with the same name, I get the error like the one at the bottom, and kibana crashes. 
If I disable the plugin, then, when I save an object that already exists, I get a popup asking for confirmation, and then it works. 

Do you think that I have something wrong in the configuration of kibana, or can you reproduce the error on your installation?

Best regards, 
pablo

```
{"error":{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[dashboard][Logstash-http-access]: version conflict, document already exists (current version [13])","index_uuid":"zPDaAmoaSQqJzMuxgxZRuA","shard":"0","index":".kibana"}],"type":"version_conflict_engine_exception","reason":"[dashboard][Logstash-http-access]: version conflict, document already exists (current version [13])","index_uuid":"zPDaAmoaSQqJzMuxgxZRuA","shard":"0","index":".kibana"},"status":409}
```

**Comment by wtakase** [comment]
Thanks. It has been fixed and new versions have been released as vX.X.X-2.

**Comment by psaiz** [comment]
Thanks! that solved the issue.
