### ISSUE TITLE
add an option to customize own-home port

### ISSUE THREAD

**Issue by fbaligand** [wtakase/kibana-own-home#76]
Currently, the own-home proxy port is 19200 and it is not configurable.
It would be nice to add a `elasticsearch.yml` property to customize this port.
For example : `own_home.port`

**Comment by wtakase** [comment]
You can use any port instead of 19200.
If you set `elasticsearch.url: http://localhost:19201`, the proxy port will be 19201.

Refer [this issue](https://github.com/wtakase/kibana-own-home/issues/20).

**Comment by fbaligand** [comment]
OK, fine !

So it would be nice to document this feature in README.md.

**Comment by wtakase** [comment]
I added it to README.md.
https://github.com/wtakase/kibana-own-home#change-own-home-port

**Comment by fbaligand** [comment]
Great => thanks !
