### ISSUE TITLE
is that possible remove the proxy-layer such as nginx

### ISSUE THREAD

**Issue by xycloud** [wtakase/kibana-own-home#8]
is that possible remove the proxy-layer such as nginx? just hook the es request

**Comment by wtakase** [comment]
Could you explain your use case?
The proxy-layer is necessary for identifying a user.

**Comment by xycloud** [comment]
i
i get the identify user from oauth authentication, this time proxy layer config is not useful

**Comment by wtakase** [comment]
If you use oauth authentication, you need to tell own-home plugin authenticated username somehow. And I guess it requires own-home modification.

**Comment by xycloud** [comment]
could you give some code introduction or hint, if i made own-home modification for this feature.

**Comment by wtakase** [comment]
Currently, the plugin fetches username from a header as follows:
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/get_kibana_index_name.js#L9-L10
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/kibana_map_uri.js#L36-L37
https://github.com/wtakase/kibana-own-home/blob/master/server/selection.js#L14-L15

If the plugin finds a username from a header, the plugin sets it to `remoteUser` variable and replaces `kibana.index` with user-specified one:
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/replace_kibana_index.js#L12-L17
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/modify_payload.js#L43-L46

I guess you can change above username fetching process to obtaining username from oauth, some how.

**Comment by xycloud** [comment]
thanks for your reply, I will try

**Comment by xycloud** [comment]
what's the core code of multi-index?
