### ISSUE TITLE
document-level tenancy

### ISSUE THREAD

**Issue by baramuse** [wtakase/kibana-own-home#80]
Hi,

it's more a question than an issue.
I just wanted to make sure I understood correctly but this plugin "only" let you have different users of Kibana having their own dashboard and visualisation over THE SAME es cluster right ?

so they all see the same data, there is no way of restricting data to the user like the x-pack (incredibly expensive) or searchguard (don't know the price but I'm doubtful) ?

Cheers.

**Comment by wtakase** [comment]
Yes, you are right.
For elasticsearch data access control, you need to use another tool such as x-pack, searchguard.

**Comment by seanziee** [comment]
Or read over rest (which I've used)

**Comment by baramuse** [comment]
What do you mean ?

**Comment by seanziee** [comment]
You can use read over rest plugin and limit users to aliases. That apparently has it's own risk but its a nice workaround

**Comment by seanziee** [comment]
A filtered alias that is

**Comment by macpoint** [comment]
I guess @seanziee mentions ReadOnlyRest ES plugin here: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin

**Comment by baramuse** [comment]
That looks awesome ! Thanks a lot for your input guys !
