### ISSUE TITLE
OwnHome with Kibana-SearchGuard plugin

### ISSUE THREAD

**Issue by waveter** [wtakase/kibana-own-home#84]
I tried to config Ownhome to use with search-guard and search-guard-kibana-plugin. I followed the config as you shown in the section https://github.com/wtakase/kibana-own-home#extract-username-from-session-instead-of-request-header-experimental, but after passing login of search-guard-kibana-plugin, there is a popup (Authentication Required) in the browser, and I cannot pass that authentication.
Do you know how to make that popup disappear?
I used the tools as below:

- Kibana-6.2.2
- ElasticSearch-6.2.2
- search-guard-6.2.2
- search-guard-kibana-plugin-6.2.2
- own_home-6.2.2

I really appreciate any help.

**Comment by ddalko** [comment]
I have same problem with you and need some help.
Have you solved the problem?
If you solved this problem, what action has been taken to solve the problem?

**Comment by waveter** [comment]
@ddalko 
Actually, I do not know there the problem come from or how to solve it.
However, after reinstall and reconfig searchguard and ownhome, it worked fine.

**Comment by ddalko** [comment]
@waveter 
Thank you for your cool advise. you are a great developer, right?
and could I see the contents of the your configuration file? (elasticsearch.yml, kibana.yml.. and so on)

**Comment by waveter** [comment]
My config files as below:
elasticsearch.yml
```
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
bootstrap.memory_lock: true
network.host: localhost
http.port: 9200
searchguard.enterprise_modules_enabled: false
searchguard.ssl.transport.pemcert_filepath: esnode.pem
searchguard.ssl.transport.pemkey_filepath: esnode-key.pem
searchguard.ssl.transport.pemtrustedcas_filepath: root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: esnode.pem
searchguard.ssl.http.pemkey_filepath: esnode-key.pem
searchguard.ssl.http.pemtrustedcas_filepath: root-ca.pem
searchguard.allow_unsafe_democertificates: true
searchguard.allow_default_init_sgindex: true
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de
searchguard.audit.type: internal_elasticsearch
searchguard.enable_snapshot_restore_privilege: true
searchguard.check_snapshot_restore_write_privileges: true
searchguard.restapi.roles_enabled: ["sg_all_access"]
cluster.name: searchguard_demo
discovery.zen.minimum_master_nodes: 1
node.max_local_storage_nodes: 3
```
kibana.yml
```
server.port: 5601
server.host: "0.0.0.0"
elasticsearch.url: "https://localhost:9200"
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
elasticsearch.ssl.verificationMode: none
server.defaultRoute: /app/own_home
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ sgtenant, cookie, authorization ]
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.elasticsearch.url: https://localhost:9200
own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
searchguard.cookie.secure: false
searchguard.cookie.password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
Note that: own_home.session.secretkey and searchguard.cookie.password are 32 characters, it need to be exactly the same value (you can keep xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx or change it)
Hope this help

**Comment by Yullin** [comment]
@waveter what is your localhost:19200 config file looks like ,please help
