### ISSUE TITLE
Why does this plugin need "this proxy"? 

### ISSUE THREAD

**Issue by nick-george** [wtakase/kibana-own-home#9]
Hi Wataru,

Props for writing what looks to be a very useful plugin for Kibana. 

I'm a little confused as to why you need to run a backend proxy that fixes up the index that kibana is using. Is it because plugins don't have access to set the Kibana index? Or is the underlying kibana index so fundamental that changing it requires a restart of Kibana? Have you looked into changing the index that Kibana is using at runtime?   

I'll give you a little idea of my use case. Each user of kibana would need to have access to all indexes (but it is still handy to be able to control who has access to what). The most useful feature is being able to seamlessly switch the underlying elastic indices, so that all our dashboards etc work exactly the same, but with different underlying data. Does that make sense? Is this possible with your plugin? 

It would also be cool if we could set custom names for each kibana index, e.g .kibana_user01 shows up in the UI as "dataset_01". Is this already possible? 

Cheers, 
Nick

**Comment by wtakase** [comment]
> I'm a little confused as to why you need to run a backend proxy that fixes up the index that kibana is using. Is it because plugins don't have access to set the Kibana index?

Yes, currently I have no idea to set `kibana.index` dynamically without the proxy.

> The most useful feature is being able to seamlessly switch the underlying elastic indices, so that all our dashboards etc work exactly the same, but with different underlying data.

Create the same dashboards on several `kibana.index` and set different elasticsearch index patterns on each `kibana.index`. When you switch `kibana.index`, the dashboards are same but elasticsearch indices becomes different.

> It would also be cool if we could set custom names for each kibana index, e.g .kibana_user01 shows up in the UI as "dataset_01". Is this already possible?

Not supported.
