### ISSUE TITLE
Own_home + Seachguard not creating index and using default

### ISSUE THREAD

**Issue by Xosmond** [wtakase/kibana-own-home#94]
I have completed follow the instructions and i got the user loged in using the serachguard plugin basic auth.

But all users are using the same .kibana index, even when inside own_home tells that is using ".kibana_user" index. Also when i set permissions only for his kibana index ".kibana_user", i got an 500 error,

Looks like own_home is not creating the index.

I created the index for own_home, but also the same error, also looks like own_home is not changing the .kibana index to .kibana_user

All in version 6.2.4

**Comment by rdrgporto** [comment]
Hi @Xosmond

I fixed this issue by using **admin user** to authenticate with **Elasticsearch**. 

```
# Kibana
server.port: 5601
server.host: "0.0.0.0"
# Search Guard
elasticsearch.requestHeadersWhitelist: [ cookie, authorization ]
elasticsearch.username: "admin"
elasticsearch.password: "admin"
elasticsearch.ssl.verificationMode: none
# Own Home
server.defaultRoute: /app/own_home
elasticsearch.url: http://localhost:19200
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.elasticsearch.url: https://localhost:9200
own_home.session.secretkey: "123567818187654rwrwfsfshdhdhtegdhfzftdhncn"
own_home.local.groups: []
searchguard.cookie.secure: false
searchguard.cookie.password: "123567818187654rwrwfsfshdhdhtegdhfzftdhncn"
```

Regards 🖖
